#!/usr/bin/env node
// Summarises project/metrics/sessions.jsonl (written by the session-end agent hook).
// Usage: node tooling/scripts/session-report.mjs [--days 30] [--write]
//   --write  also writes project/metrics/report.md (front-matter type: metrics) for the DocSaga sync.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { root, today } from './lib/repo.mjs';

const args = process.argv.slice(2);
const days = Number(args[args.indexOf('--days') + 1]) || 30;
const path = join(root, 'project/metrics/sessions.jsonl');
const sessions = existsSync(path)
  ? readFileSync(path, 'utf8').split('\n').filter(Boolean).flatMap((line) => {
      try {
        return [JSON.parse(line)];
      } catch {
        return [];
      }
    })
  : [];
const since = new Date(Date.now() - days * 86_400_000).toISOString();
const recent = sessions.filter((session) => (session.ended ?? '') >= since);

const tokenTotal = (tokens) => (tokens && typeof tokens === 'object' ? Object.entries(tokens).filter(([key]) => key !== 'total').reduce((sum, [, value]) => sum + (Number(value) || 0), 0) : null);
const groups = new Map();
for (const session of recent) {
  const key = `${session.agent} | ${(session.models ?? []).join(', ') || 'unknown'}`;
  const group = groups.get(key) ?? { sessions: 0, minutes: 0, commits: 0, tokens: 0, unavailable: 0, failedGates: 0 };
  group.sessions++;
  group.minutes += session.minutes ?? 0;
  group.commits += session.commits?.length ?? 0;
  const total = tokenTotal(session.tokens);
  if (total === null) group.unavailable++;
  else group.tokens += total;
  if (session.last_gate && !session.last_gate.ok) group.failedGates++;
  groups.set(key, group);
}

const fmt = (value) => value.toLocaleString('en-US');
const rows = [...groups.entries()].map(([key, group]) => `| ${key.replace(' | ', ' | ')} | ${group.sessions} | ${group.minutes} | ${group.commits} | ${fmt(group.tokens)}${group.unavailable ? ` (+${group.unavailable} unavailable)` : ''} | ${group.failedGates} |`);
const table = ['| Agent | Models | Sessions | Minutes | Commits | Tokens (exact) | Ended with failing gate |', '|---|---|---|---|---|---|---|', ...rows].join('\n');
const body = `# Session metrics\n\nLast ${days} days, ${recent.length} session(s) of ${sessions.length} recorded. Generated by \`tooling/scripts/session-report.mjs\` from \`project/metrics/sessions.jsonl\`; tokens are exact counts from the agents' transcripts or marked unavailable, never estimated.\n\n${recent.length ? table : 'No sessions recorded in this period.'}\n`;
console.log(body);

if (args.includes('--write')) {
  const prefix = existsSync(join(root, 'tooling/blueprint.json')) ? JSON.parse(readFileSync(join(root, 'tooling/blueprint.json'), 'utf8')).values?.PREFIX : null;
  const frontMatter = ['---', `id: ${prefix ?? 'PRJ'}-REC-metrics`, 'type: metrics', 'title: Session metrics', 'status: current', 'owner: tooling', `updated: ${today()}`, 'wiki:', '  slug: metrics', '  page_type: metrics', '  sync: auto', '---', ''].join('\n');
  writeFileSync(join(root, 'project/metrics/report.md'), `${frontMatter}${body}`);
  console.log('wrote project/metrics/report.md');
}
