#!/usr/bin/env node
// Generates tool-specific agent files from the single source in .agents/:
//   .agents/roles/*.md   -> .claude/agents/<name>.md (model from tier) and .codex/roles/<name>.md
//   tiers                -> .codex/config.toml profiles t1/t2/t3 (model_reasoning_effort, optional model)
//   roles                -> .codex/agents/<name>.toml (discoverable Codex subagents)
//   .agents/codex/       -> Codex developer instructions and hooks.json
//   .agents/skills/*     -> each directory in skillTargets (default .claude/skills)
// Usage: node tooling/scripts/sync-agents.mjs [--check]   (--check fails if generated files differ)
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { readFrontMatter } from './lib/yaml.mjs';
import { readJson, report, root } from './lib/repo.mjs';

const check = process.argv.includes('--check');
const config = readJson('.agents/agents.config.json');
const header = (comment) => `${comment} Generated by tooling/scripts/sync-agents.mjs from .agents/. Do not edit.`;
const outputs = new Map();

const rolesDir = join(root, '.agents/roles');
const roles = existsSync(rolesDir) ? readdirSync(rolesDir).filter((name) => name.endsWith('.md')).sort() : [];
const errors = [];
// JSON string escaping is compatible with TOML basic strings for these text inputs.
const tomlString = (value) => JSON.stringify(value);
const codexInstructionsPath = join(root, '.agents/codex/instructions.md');
const codexInstructions = existsSync(codexInstructionsPath) ? readFileSync(codexInstructionsPath, 'utf8').trim() : '';
const roleNames = new Set();

for (const file of roles) {
  const { data, body } = readFrontMatter(readFileSync(join(rolesDir, file), 'utf8'));
  const tier = config.tiers[data?.tier];
  if (!data?.name || !data?.description || !tier) {
    errors.push(`.agents/roles/${file}: needs name, description and a tier in ${Object.keys(config.tiers).join('/')}`);
    continue;
  }
  if (!/^[a-z][a-z0-9-]*$/.test(data.name) || roleNames.has(data.name)) {
    errors.push(`.agents/roles/${file}: name must be unique and use lowercase letters, digits and hyphens`);
    continue;
  }
  roleNames.add(data.name);
  const tools = [...new Set((data.tools ?? []).flatMap((tool) => config.toolMap[tool] ?? []))];
  const claudeLines = ['---', `name: ${data.name}`, `description: ${JSON.stringify(data.description)}`];
  if (tools.length) claudeLines.push(`tools: ${tools.join(', ')}`);
  claudeLines.push(`model: ${tier.claude.model}`, '---', `<!-- ${header('').trim()} Tier ${data.tier}. -->`, '', body.trim(), '');
  outputs.set(`.claude/agents/${data.name}.md`, claudeLines.join('\n'));
  outputs.set(
    `.codex/roles/${data.name}.md`,
    [`<!-- ${header('').trim()} Run with: codex --profile ${data.tier.toLowerCase()} -->`, `# ${data.name} (${data.tier}, ${tier.label})`, '', data.description, '', body.trim(), ''].join('\n')
  );
  const agent = [`# ${header('').trim()}`, `name = ${tomlString(data.name)}`, `description = ${tomlString(data.description)}`];
  if (tier.codex.model) agent.push(`model = ${tomlString(tier.codex.model)}`);
  agent.push(`model_reasoning_effort = ${tomlString(tier.codex.effort)}`);
  // Test runners must write build artifacts, so only pure read roles get a read-only sandbox.
  if (!(data.tools ?? []).includes('edit') && !(data.tools ?? []).includes('shell')) agent.push('sandbox_mode = "read-only"');
  agent.push(`developer_instructions = ${tomlString([codexInstructions, body.trim()].filter(Boolean).join('\n\n'))}`, '');
  outputs.set(`.codex/agents/${data.name}.toml`, agent.join('\n'));
}

const toml = [`# ${header('').trim()}`, '# Select a tier with `codex --profile t1|t2|t3`. Set a model per tier in .agents/agents.config.json.', ''];
if (codexInstructions) toml.push(`developer_instructions = ${tomlString(codexInstructions)}`, '');
const codexHooksPath = join(root, '.agents/codex/hooks.json');
if (existsSync(codexHooksPath)) {
  const hooks = JSON.parse(readFileSync(codexHooksPath, 'utf8'));
  outputs.set('.codex/hooks.json', `${JSON.stringify({ ...hooks, description: header('').trim() }, null, 2)}\n`);
  toml.push('[features]', 'hooks = true', '');
}
for (const [name, tier] of Object.entries(config.tiers)) {
  toml.push(`[profiles.${name.toLowerCase()}]`);
  if (tier.codex.model) toml.push(`model = ${JSON.stringify(tier.codex.model)}`);
  toml.push(`model_reasoning_effort = ${JSON.stringify(tier.codex.effort)}`, '');
}
outputs.set('.codex/config.toml', toml.join('\n'));

const skillsDir = join(root, '.agents/skills');
const copyTree = (from, to) => {
  for (const name of readdirSync(from).sort()) {
    const source = join(from, name);
    if (statSync(source).isDirectory()) copyTree(source, `${to}/${name}`);
    else outputs.set(`${to}/${name}`, readFileSync(source, 'utf8'));
  }
};
if (existsSync(skillsDir)) for (const target of config.skillTargets) copyTree(skillsDir, target);

const managedDirs = ['.claude/agents', '.codex/roles', '.codex/agents', ...config.skillTargets];
const existing = [];
const walk = (dir) => {
  if (!existsSync(join(root, dir))) return;
  for (const name of readdirSync(join(root, dir))) {
    const path = `${dir}/${name}`;
    if (statSync(join(root, path)).isDirectory()) walk(path);
    else existing.push(path);
  }
};
managedDirs.forEach(walk);

// Reject invalid sources before writing or deleting any generated output.
if (errors.length) {
  report('agents sync', errors);
  process.exit(1);
}

if (check) {
  for (const [path, content] of outputs) {
    const full = join(root, path);
    if (!existsSync(full)) errors.push(`${path} is missing; run node tooling/scripts/sync-agents.mjs`);
    else if (readFileSync(full, 'utf8').replace(/\r\n/g, '\n') !== content) errors.push(`${path} differs from .agents/; edit .agents/ and re-run sync-agents`);
  }
  for (const path of existing) if (!outputs.has(path)) errors.push(`${path} is not generated from .agents/; remove it or add a source`);
  report('agents sync', errors, { okMessage: `${outputs.size} generated file(s) match` });
} else {
  for (const path of existing) if (!outputs.has(path)) rmSync(join(root, path));
  for (const [path, content] of outputs) {
    mkdirSync(dirname(join(root, path)), { recursive: true });
    writeFileSync(join(root, path), content);
  }
  report('agents sync', errors, { okMessage: `wrote ${outputs.size} file(s)` });
}
