// Isolation for compose-smoke.mjs: the verification stack must not collide with a running development
// stack. Given the resolved Compose services (`docker compose config --format json`), builds an override
// that drops fixed container names and publishes every port on a free host port, and maps the smoke
// URLs to those ports. Needs Docker Compose 2.24+ (!reset and !override tags).

/** @returns {{ yaml: string, portMap: Map<number, number> }} */
export function smokeOverride(services, nextFreePort) {
  const portMap = new Map();
  const lines = ['# Generated by compose-smoke.mjs for an isolated verification stack. Do not edit.', 'services:'];
  for (const [name, service] of Object.entries(services ?? {})) {
    const ports = (service.ports ?? []).filter((port) => port.published);
    if (!ports.length && !service.container_name) continue;
    lines.push(`  ${JSON.stringify(name)}:`);
    if (service.container_name) lines.push('    container_name: !reset null');
    if (ports.length) {
      lines.push('    ports: !override');
      for (const port of ports) {
        const published = Number(port.published);
        if (!portMap.has(published)) portMap.set(published, nextFreePort());
        const host = port.host_ip ? `${port.host_ip}:` : '';
        lines.push(`      - ${JSON.stringify(`${host}${portMap.get(published)}:${port.target}${port.protocol && port.protocol !== 'tcp' ? `/${port.protocol}` : ''}`)}`);
      }
    }
  }
  return { yaml: `${lines.join('\n')}\n`, portMap };
}

/** Rewrites http(s)://host:port URLs whose port was remapped. */
export function remapUrl(url, portMap) {
  return url.replace(/^(https?:\/\/[^/:]+):(\d+)/, (match, origin, port) => (portMap.has(Number(port)) ? `${origin}:${portMap.get(Number(port))}` : match));
}
